/**
 * Mock data for UI development.
 * Replaces all API calls so the frontend can be developed without a backend.
 */

// ─── AAS Templates ──────────────────────────────────────────────────────────

export const MOCK_AAS_TEMPLATES = [
  {
    aasmodel_seq: "1",
    aasmodel_name: "Robot Arm Controller",
    aasmodel_id: "urn:keti:aas:robot-arm-001",
    aasmodel_template_id: "urn:keti:template:robot-arm-v1",
    description: "AAS template for industrial robot arm control units",
    category_name: "Manufacturing",
    category_seq: "1",
    status: "published",
    status_nm: "Published",
    version: "1.0",
    create_user_seq: 1,
    aasmodel_img: null,
    mime_type: null,
  },
  {
    aasmodel_seq: "2",
    aasmodel_name: "Smart Sensor Hub",
    aasmodel_id: "urn:keti:aas:sensor-hub-002",
    aasmodel_template_id: "urn:keti:template:sensor-hub-v2",
    description: "Unified template for IoT sensor aggregation hubs",
    category_name: "IoT Devices",
    category_seq: "2",
    status: "published",
    status_nm: "Published",
    version: "2.1",
    create_user_seq: 1,
    aasmodel_img: null,
    mime_type: null,
  },
  {
    aasmodel_seq: "3",
    aasmodel_name: "Electric Motor Drive",
    aasmodel_id: "urn:keti:aas:motor-drive-003",
    aasmodel_template_id: "urn:keti:template:motor-drive-v1",
    description: "Template for variable frequency drive systems",
    category_name: "Drives",
    category_seq: "3",
    status: "draft",
    status_nm: "Draft",
    version: "0.9",
    create_user_seq: 2,
    aasmodel_img: null,
    mime_type: null,
  },
  {
    aasmodel_seq: "4",
    aasmodel_name: "HVAC Controller",
    aasmodel_id: "urn:keti:aas:hvac-004",
    aasmodel_template_id: "urn:keti:template:hvac-v1",
    description: "Heating, ventilation and air conditioning asset template",
    category_name: "Facility",
    category_seq: "4",
    status: "published",
    status_nm: "Published",
    version: "1.3",
    create_user_seq: 1,
    aasmodel_img: null,
    mime_type: null,
  },
  {
    aasmodel_seq: "5",
    aasmodel_name: "Conveyor Belt System",
    aasmodel_id: "urn:keti:aas:conveyor-005",
    aasmodel_template_id: "urn:keti:template:conveyor-v1",
    description: "Template for automated conveyor belt assemblies",
    category_name: "Manufacturing",
    category_seq: "1",
    status: "temporary",
    status_nm: "Temporary",
    version: "0.1",
    create_user_seq: 3,
    aasmodel_img: null,
    mime_type: null,
  },
  {
    aasmodel_seq: "6",
    aasmodel_name: "CNC Machine Tool",
    aasmodel_id: "urn:keti:aas:cnc-006",
    aasmodel_template_id: "urn:keti:template:cnc-v3",
    description: "Template for Computer Numerical Control machine tools",
    category_name: "Manufacturing",
    category_seq: "1",
    status: "published",
    status_nm: "Published",
    version: "3.0",
    create_user_seq: 1,
    aasmodel_img: null,
    mime_type: null,
  },
];

// ─── Submodel Templates ──────────────────────────────────────────────────────

export const MOCK_SUBMODEL_TEMPLATES = [
  {
    submodel_seq: "1",
    submodel_name: "Nameplate",
    submodel_id: "urn:keti:sm:nameplate-001",
    submodel_template_id: "urn:keti:template:sm-nameplate-v1",
    submodel_semantic_id: "https://admin-shell.io/zvei/nameplate/2/0/Nameplate",
    description: "Digital nameplate for industrial equipment identification",
    category_name: "Identification",
    category_seq: "1",
    status: "published",
    status_nm: "Published",
    submodel_version: "2.0",
    create_user_seq: 1,
    submodel_img: null,
    mime_type: null,
  },
  {
    submodel_seq: "2",
    submodel_name: "Technical Data",
    submodel_id: "urn:keti:sm:technical-data-002",
    submodel_template_id: "urn:keti:template:sm-technical-v1",
    submodel_semantic_id: "https://admin-shell.io/IDTA/2/0/TechnicalData",
    description: "Technical specifications and performance parameters",
    category_name: "Technical",
    category_seq: "2",
    status: "published",
    status_nm: "Published",
    submodel_version: "1.2",
    create_user_seq: 1,
    submodel_img: null,
    mime_type: null,
  },
  {
    submodel_seq: "3",
    submodel_name: "Maintenance Record",
    submodel_id: "urn:keti:sm:maintenance-003",
    submodel_template_id: "urn:keti:template:sm-maintenance-v1",
    submodel_semantic_id: "https://admin-shell.io/IDTA/2/0/MaintenanceRecord",
    description: "Maintenance schedule, history and service records",
    category_name: "Operations",
    category_seq: "3",
    status: "draft",
    status_nm: "Draft",
    submodel_version: "0.8",
    create_user_seq: 2,
    submodel_img: null,
    mime_type: null,
  },
  {
    submodel_seq: "4",
    submodel_name: "Documentation",
    submodel_id: "urn:keti:sm:documentation-004",
    submodel_template_id: "urn:keti:template:sm-docs-v2",
    submodel_semantic_id: "https://admin-shell.io/IDTA/2/0/HandoverDocumentation",
    description: "Handover documentation and manuals",
    category_name: "Documentation",
    category_seq: "4",
    status: "published",
    status_nm: "Published",
    submodel_version: "2.0",
    create_user_seq: 1,
    submodel_img: null,
    mime_type: null,
  },
  {
    submodel_seq: "5",
    submodel_name: "Energy Consumption",
    submodel_id: "urn:keti:sm:energy-005",
    submodel_template_id: "urn:keti:template:sm-energy-v1",
    submodel_semantic_id: "https://admin-shell.io/IDTA/2/0/EnergyManagement",
    description: "Energy consumption monitoring and efficiency data",
    category_name: "Sustainability",
    category_seq: "5",
    status: "published",
    status_nm: "Published",
    submodel_version: "1.0",
    create_user_seq: 1,
    submodel_img: null,
    mime_type: null,
  },
];

// ─── AAS Instances ───────────────────────────────────────────────────────────

export const MOCK_INSTANCES = [
  {
    instance_seq: "1",
    instance_name: "Line-A Robot #01",
    description: "Production line A robot arm unit 1",
    aasmodel_seq: "1",
    aasmodel_name: "Robot Arm Controller",
    aasmodel_id: "urn:keti:aas:robot-arm-001",
    aasmodel_template_id: "urn:keti:template:robot-arm-v1",
    category_name: "Manufacturing",
    verification: "success",
    status: "published",
    status_nm: "Published",
    user_id: "admin",
    create_user_seq: 1,
    server_created: true,
    server_path: "/data/servers/instance_1",
    create_date: "2025-01-15T10:30:00",
    last_mod_date: "2025-03-20T14:22:00",
  },
  {
    instance_seq: "2",
    instance_name: "Sensor Node B-12",
    description: "IoT sensor hub node installed in building B floor 1",
    aasmodel_seq: "2",
    aasmodel_name: "Smart Sensor Hub",
    aasmodel_id: "urn:keti:aas:sensor-hub-002",
    aasmodel_template_id: "urn:keti:template:sensor-hub-v2",
    category_name: "IoT Devices",
    verification: "success",
    status: "published",
    status_nm: "Published",
    user_id: "user01",
    create_user_seq: 3,
    server_created: false,
    server_path: null,
    create_date: "2025-02-10T09:15:00",
    last_mod_date: "2025-02-10T09:15:00",
  },
  {
    instance_seq: "3",
    instance_name: "Motor Drive VFD-03",
    description: "Variable frequency drive for pump motor section 3",
    aasmodel_seq: "3",
    aasmodel_name: "Electric Motor Drive",
    aasmodel_id: "urn:keti:aas:motor-drive-003",
    aasmodel_template_id: "urn:keti:template:motor-drive-v1",
    category_name: "Drives",
    verification: "fail",
    status: "draft",
    status_nm: "Draft",
    user_id: "user02",
    create_user_seq: 3,
    server_created: false,
    server_path: null,
    create_date: "2025-03-05T16:45:00",
    last_mod_date: "2025-04-01T11:00:00",
  },
  {
    instance_seq: "4",
    instance_name: "HVAC Unit Floor 3",
    description: "Central HVAC controller for third floor office area",
    aasmodel_seq: "4",
    aasmodel_name: "HVAC Controller",
    aasmodel_id: "urn:keti:aas:hvac-004",
    aasmodel_template_id: "urn:keti:template:hvac-v1",
    category_name: "Facility",
    verification: "success",
    status: "published",
    status_nm: "Published",
    user_id: "admin",
    create_user_seq: 1,
    server_created: true,
    server_path: "/data/servers/instance_4",
    create_date: "2025-01-28T08:00:00",
    last_mod_date: "2025-05-01T13:30:00",
  },
];

// ─── Published / Distribute ──────────────────────────────────────────────────

export const MOCK_DISTRIBUTED = [
  {
    target_seq: "1",
    target_name: "Robot Arm Controller",
    target_version: "1.0",
    ty: "aasmodel",
    status: "published",
    status_nm: "Published",
    tmp_seman_id: "urn:keti:template:robot-arm-v1",
    category_name: "Manufacturing",
    create_date: "2025-01-10T00:00:00",
  },
  {
    target_seq: "2",
    target_name: "Smart Sensor Hub",
    target_version: "2.1",
    ty: "aasmodel",
    status: "published",
    status_nm: "Published",
    tmp_seman_id: "urn:keti:template:sensor-hub-v2",
    category_name: "IoT Devices",
    create_date: "2025-02-01T00:00:00",
  },
  {
    target_seq: "3",
    target_name: "Nameplate",
    target_version: "2.0",
    ty: "submodel",
    status: "published",
    status_nm: "Published",
    tmp_seman_id: "https://admin-shell.io/zvei/nameplate/2/0/Nameplate",
    category_name: "Identification",
    create_date: "2025-01-15T00:00:00",
  },
  {
    target_seq: "4",
    target_name: "Technical Data",
    target_version: "1.2",
    ty: "submodel",
    status: "published",
    status_nm: "Published",
    tmp_seman_id: "https://admin-shell.io/IDTA/2/0/TechnicalData",
    category_name: "Technical",
    create_date: "2025-03-01T00:00:00",
  },
  {
    target_seq: "5",
    target_name: "CNC Machine Tool",
    target_version: "3.0",
    ty: "aasmodel",
    status: "deprecated",
    status_nm: "Deprecated",
    tmp_seman_id: "urn:keti:template:cnc-v3",
    category_name: "Manufacturing",
    create_date: "2024-11-20T00:00:00",
  },
];

// ─── Users ───────────────────────────────────────────────────────────────────

export const MOCK_USERS = [
  {
    user_seq: 1,
    user_id: "admin",
    user_name: "Admin User",
    user_group_seq: 1,
    user_group_name: "System Manager",
    status: "Y",
    status_nm: "Activate",
    user_phonenumber: "010-1234-5678",
    start_timestamp: "2024-01-01T00:00:00",
    socialprovider_name: null,
    user_photo_url: "",
  },
  {
    user_seq: 2,
    user_id: "manager01",
    user_name: "Template Manager",
    user_group_seq: 2,
    user_group_name: "Template Manager",
    status: "Y",
    status_nm: "Activate",
    user_phonenumber: "010-2345-6789",
    start_timestamp: "2024-03-15T00:00:00",
    socialprovider_name: null,
    user_photo_url: "",
  },
  {
    user_seq: 3,
    user_id: "user01",
    user_name: "Kim Taehoon",
    user_group_seq: 3,
    user_group_name: "User",
    status: "Y",
    status_nm: "Activate",
    user_phonenumber: "010-3456-7890",
    start_timestamp: "2024-06-01T00:00:00",
    socialprovider_name: "Google",
    user_photo_url: "",
  },
  {
    user_seq: 4,
    user_id: "user02",
    user_name: "Park Jiyeon",
    user_group_seq: 3,
    user_group_name: "User",
    status: "Y",
    status_nm: "Activate",
    user_phonenumber: null,
    start_timestamp: "2024-08-10T00:00:00",
    socialprovider_name: null,
    user_photo_url: "",
  },
  {
    user_seq: 5,
    user_id: "user03",
    user_name: "Lee Minjae",
    user_group_seq: 3,
    user_group_name: "User",
    status: "N",
    status_nm: "Deactivate",
    user_phonenumber: null,
    start_timestamp: "2025-01-20T00:00:00",
    socialprovider_name: "Kakao",
    user_photo_url: "",
  },
];

// ─── Categories ──────────────────────────────────────────────────────────────

export const MOCK_CATEGORIES = [
  { id: "1", text: "Manufacturing" },
  { id: "2", text: "IoT Devices" },
  { id: "3", text: "Drives" },
  { id: "4", text: "Facility" },
  { id: "5", text: "Sustainability" },
];

export const MOCK_AAS_CATEGORIES = [
  { id: "101", icon: "Factory",      text: "Manufacturing Equipment", count: 3 },
  { id: "102", icon: "Zap",          text: "Drives & Motors",         count: 2 },
  { id: "103", icon: "Cpu",          text: "Sensors & IoT",           count: 2 },
  { id: "104", icon: "Building2",    text: "Facility",                count: 2 },
  { id: "105", icon: "Leaf",         text: "Energy & Sustainability", count: 1 },
  { id: "106", icon: "Bot",          text: "Robotics & Automation",   count: 2 },
];

export const MOCK_SM_CATEGORIES = [
  { id: "201", icon: "Tag",           text: "Nameplate",               count: 4 },
  { id: "202", icon: "FileBarChart2", text: "Technical Data",           count: 5 },
  { id: "203", icon: "BookOpen",      text: "Documentation",            count: 6 },
  { id: "204", icon: "IdCard",        text: "Digital Nameplate",        count: 3 },
  { id: "205", icon: "Sprout",        text: "Carbon Footprint",         count: 4 },
  { id: "206", icon: "ClipboardList", text: "Handover Documentation",   count: 6 },
];

// ─── Home Stats ──────────────────────────────────────────────────────────────

export const MOCK_PUBLISHED_COUNT = {
  aasmodel: { ty: "aasmodel", count: 12 },
  submodel: { ty: "submodel", count: 28 },
  instance: { ty: "instance", count: 47 },
};
